# Generated by Django 3.2.15 on 2022-11-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image_actor',
            field=models.ImageField(blank=True, upload_to='actors/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_movie',
            field=models.ImageField(blank=True, upload_to='movies/', verbose_name='Постер'),
        ),
    ]
