# Generated by Django 3.2.15 on 2022-12-01 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20221123_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='TimeShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_show', models.DateTimeField(blank=True, null=True, verbose_name='Дата/Время показа')),
                ('price_ticket', models.IntegerField(blank=True, null=True, verbose_name='Стоимость билета')),
                ('title_film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='film_title_movie', to='mainapp.movie', verbose_name='Название фильма')),
            ],
            options={
                'verbose_name': 'Дата/Время Показа',
                'verbose_name_plural': 'Дата/Время показов',
            },
        ),
        migrations.CreateModel(
            name='RegistrationVisitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_visitor', models.CharField(max_length=256, verbose_name='Посетитель')),
                ('last_name_visitor', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('email_visitor', models.CharField(max_length=256, verbose_name='Email')),
                ('data_time_show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_time_show', to='mainapp.timeshow', verbose_name='Дата/Время показа')),
                ('place_visitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='place_visitor_view', to='mainapp.hallplace', verbose_name='Место')),
                ('price_ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_ticket_visitor', to='mainapp.timeshow', verbose_name='Стоимость билета')),
                ('title_films', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='title_film_view_visitor', to='mainapp.timeshow', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Регистрация Посетителя',
                'verbose_name_plural': 'Регистрация Посетителей',
            },
        ),
    ]
