# Generated by Django 3.2.15 on 2022-12-03 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_hallplace_registrationvisitors_timeshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationvisitors',
            name='title_films',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='title_film_view_visitor', to='mainapp.movie', verbose_name='Название'),
        ),
    ]
