# Generated by Django 3.2.15 on 2022-12-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_registrationvisitors_title_films'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallplace',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='timeshow',
            name='date_time_show',
            field=models.DateTimeField(blank=True, null=True, unique=True, verbose_name='Дата/Время показа'),
        ),
    ]
