# Generated by Django 3.2.15 on 2022-12-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20221204_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='time_show_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.timeshow', verbose_name='Время показа'),
        ),
    ]
