# Generated by Django 3.2.15 on 2022-12-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_movie_time_show_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='time_show_movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='time_show_movie',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.TimeShow', verbose_name='Время показа'),
        ),
    ]
