# Generated by Django 3.2.15 on 2022-12-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20221204_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='time_show_movie',
        ),
    ]
