# Generated by Django 3.2.15 on 2022-12-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_movie_time_show_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationvisitors',
            name='place_visitor',
        ),
        migrations.AddField(
            model_name='registrationvisitors',
            name='place_visitor',
            field=models.ManyToManyField(related_name='place_visitor_view', to='mainapp.HallPlace', verbose_name='Место'),
        ),
    ]
