# Generated by Django 3.2.15 on 2022-12-13 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_hallplace_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationvisitors',
            name='title_films',
        ),
        migrations.RemoveField(
            model_name='timeshow',
            name='title_film',
        ),
        migrations.AddField(
            model_name='registrationvisitors',
            name='title_movie',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='title_movie_view_visitor', to='mainapp.movie', verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeshow',
            name='title_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='title_movie_date_show', to='mainapp.movie', verbose_name='Название фильма'),
        ),
    ]
