# Generated by Django 3.2.15 on 2022-12-13 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20221213_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationvisitors',
            name='data_time_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie_data_time_show', to='mainapp.timeshow', verbose_name='Дата/Время показа'),
        ),
        migrations.AlterField(
            model_name='timeshow',
            name='title_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='title_movie_date_shownoe', to='mainapp.movie', verbose_name='Название фильма'),
        ),
    ]
